on:
  workflow_run:
    workflows: ["Bump package version"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    needs: bump-package-version
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: ^6.24.1
      - run: pnpm install
      - run: pnpm run ci
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}