name: Publish Package to npmjs
on:
  push:
    tags:
      - '*'
jobs:
  bump-package-version:
    name: 'Bump package version'
    needs: create-tagged-release
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Bump manifest version
        run: node .github/actions/bump-package-version.js
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
      - name: Push manifest change
        uses: EndBug/add-and-commit@v8
        with:
          add: package.json
          push: true
          author_name: Manifest Bumper
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore(bump-manifest): Bump package version to ${{ env.RELEASE_VERSION }}'
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        run: echo ::set-output name=VERSION_TAG::${GITHUB_REF/refs\/tags\//}
        id: get_tag
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: ^6.24.1
      - run: pnpm install
      - run: pnpm run ci
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}